TRAP_CELL = "T"
GEM_CELL = "G"
EMPTY_CELL = "_"
NUMBER_CELL = "N"

DEFAULT_TRAP_PROBABILITY = 0.25

ZERO_COUNT = 0
ZERO_LENGTH = 0
ZERO_VALUE = 0

MENU_OPTIONS_GENERATE_MAP = 0
MENU_OPTIONS_SOLVE_MAP = 1
MENU_OPTIONS_EXIT = 2

FILE_READ_MODE = "r"
FILE_WRITE_MODE = "w"

CNF_STARTING_VAR = 1